FACTOR = 1
WIDTH, HEIGHT = round(540 * FACTOR), round(540 * FACTOR)
ROWS, COLS = 3,3
assert ROWS == COLS, "Rows and Cols should be equal"
TILE_SIZE = round(WIDTH / COLS)

FPS = 60

LINE_WIDTH = round(15 * FACTOR)
CIRCLE_WIDTH = round(15 * FACTOR)
CIRCLE_RADIUS = round(45 * FACTOR)
CROSS_WIDTH = round(15 * FACTOR)
CROSS_LENGTH = round(99 * FACTOR)
WIN_WIDTH = round(15 * FACTOR)
OFFSET = round(70 * FACTOR)

BG_COLOR = (28, 170, 156)
LINE_COLOR = (23, 145, 135)
CIRCLE_COLOR = (239, 231, 200)
CROSS_COLOR = (66, 66, 66)

BUTTON_SIZE = (round(250 * FACTOR), round(60 * FACTOR))
BUTTON_COLOR = (16, 101, 94)
BUTTON_RADIUS = 5
BUTTON_BORDER = False
BUTTON_HOVER = True

BUTTON_FONT_NAME = 'consolas'
BUTTON_FONT_COLOR = (250, 248, 239)
BUTTON_FONT_SIZE = round(35 * FACTOR)

HEADER_FONT_NAME = 'cambria'
HEADER_FONT_COLOR = (66, 66, 66)
HEADER_FONT_SIZE = round(65 * FACTOR)

NORMAL_FONT_NAME = 'consolas'
NORMAL_FONT_COLOR = (66, 66, 66)
NORMAL_FONT_SIZE = round(25 * FACTOR)

if BUTTON_BORDER:
    BUTTON_BORDER_WIDTH = round(10 * FACTOR)
    BUTTON_BORDER_COLOR = (66, 66, 66)

if BUTTON_HOVER:
    HOVER_COLOR = (250, 248, 239)
    HOVER_TEXT_COLOR = (16, 101, 94)

SHARP_EDGE_CROSS = False
SHARP_EDGE_WIN = False


DATA_FILE = 'Game Variables.dat'
CLICK_SOUND_FILE = 'Assets/Click Sound.wav'
WIN_SOUND_FILE = 'Assets/Win Sound.mp3'
ICON_FILE = 'Assets/Game Icon.png'